
import { SeoAnalysis } from "../types";

export const analyzeContent = (htmlContent: string, targetKeywords: string): SeoAnalysis => {
  // 1. Setup default response
  const result: SeoAnalysis = {
    score: 100,
    wordCount: 0,
    readingTime: 0,
    keywordDensity: 0,
    keywordCount: 0,
    issues: {
      critical: [],
      warning: [],
      good: []
    }
  };

  if (!htmlContent) return result;

  // 2. Parse HTML safely
  const parser = new DOMParser();
  const doc = parser.parseFromString(htmlContent, 'text/html');

  // Remove Style tags to avoid counting CSS as words
  const styles = doc.querySelectorAll('style');
  styles.forEach(style => style.remove());
  
  // Remove Script tags
  const scripts = doc.querySelectorAll('script');
  scripts.forEach(script => script.remove());

  // Get Clean Text
  const plainText = doc.body.textContent || "";
  const words = plainText.trim().split(/\s+/).filter(w => w.length > 0);
  result.wordCount = words.length;
  result.readingTime = Math.ceil(result.wordCount / 200); // Average reading speed

  // 3. Keyword Analysis
  // Take the first keyword if multiple are comma-separated
  const primaryKeyword = targetKeywords.split(',')[0].trim().toLowerCase();
  
  if (primaryKeyword) {
    const regex = new RegExp(primaryKeyword.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi');
    const matches = plainText.match(regex);
    result.keywordCount = matches ? matches.length : 0;
    
    if (result.wordCount > 0) {
      result.keywordDensity = parseFloat(((result.keywordCount / result.wordCount) * 100).toFixed(2));
    }

    // --- STRIKE INTENT & KEYWORD VALIDATIE ---

    // A. Basis Keyword Aanwezigheid
    if (result.keywordCount === 0) {
      result.issues.critical.push(`Zoekwoord "${primaryKeyword}" niet gevonden in tekst.`);
      result.score -= 20;
    } else if (result.keywordDensity > 3.5) {
      result.issues.warning.push(`Keyword density is hoog (${result.keywordDensity}%). Pas op voor keyword stuffing.`);
      result.score -= 5;
    } else {
      result.issues.good.push(`Zoekwoord komt ${result.keywordCount} keer voor (${result.keywordDensity}%).`);
    }

    // B. First 100 Words Rule (GEO Snippet Optimization)
    const first100Words = words.slice(0, 100).join(' ').toLowerCase();
    if (!first100Words.includes(primaryKeyword)) {
        result.issues.critical.push("GEO/SEO FAIL: Het hoofdzoekwoord MOET in de eerste 100 woorden staan.");
        result.score -= 15;
    } else {
        result.issues.good.push("Perfect: Zoekwoord staat in de introductie (Snippet-ready).");
    }

    // C. H1 Check
    const h1 = doc.querySelector('h1');
    if (h1) {
      if (!h1.textContent?.toLowerCase().includes(primaryKeyword)) {
         result.issues.critical.push("H1 FAIL: Zoekwoord moet exact in de H1 titel staan.");
         result.score -= 15;
      } else {
         result.issues.good.push("Zoekwoord aanwezig in de H1.");
      }
    } else {
         // Fallback look for H2 if no H1 found (sometimes editor structure varies)
         const h2 = doc.querySelector('h2');
         if (!h2 || !h2.textContent?.toLowerCase().includes(primaryKeyword)) {
            result.issues.warning.push("Zoekwoord niet gevonden in de belangrijkste titel.");
            result.score -= 10;
         }
    }

    // D. Transactional Verb Focus (Intent Matching)
    const transactionalVerbs = ['kopen', 'bestellen', 'graveren', 'maken', 'ontwerpen', 'snijden', 'laten', 'personaliseren'];
    const keywordHasAction = transactionalVerbs.some(verb => primaryKeyword.includes(verb));
    
    if (keywordHasAction) {
        // If the keyword implies action, headers must verify this action
        const h1Text = h1?.textContent?.toLowerCase() || "";
        const verbInH1 = transactionalVerbs.some(verb => h1Text.includes(verb));
        
        if (!verbInH1) {
             result.issues.warning.push("INTENT MISMATCH: Je zoekwoord is transactioneel (actie). Zorg dat de H1 een werkwoord bevat (bijv. 'Laten graveren').");
             result.score -= 10;
        } else {
             result.issues.good.push("Intent Match: Actiegericht zoekwoord correct gebruikt in kop.");
        }
    }

    // E. Meta Description Match (CTR Optimization)
    // We try to extract the meta description from the HTML comment or the p-tag generated by App.tsx
    // Format in HTML: <!-- ... META DESC: [Description] ... -->
    const metaMatch = htmlContent.match(/META DESC:\s*(.*?)(?:\n|-->)/);
    if (metaMatch && metaMatch[1]) {
        const metaDesc = metaMatch[1].trim().toLowerCase();
        
        if (!metaDesc.includes(primaryKeyword)) {
             result.issues.warning.push("META FAIL: Het zoekwoord staat niet in de Meta Description.");
             result.score -= 10;
        } else if (metaDesc.indexOf(primaryKeyword) > 40) {
             // If keyword appears after the ~40th character, warn about CTR
             result.issues.warning.push("CTR TIP: Zet het zoekwoord vooraan in de Meta Description voor meer klikken.");
             result.score -= 5;
        } else {
             result.issues.good.push("Meta Description is geoptimaliseerd voor CTR.");
        }
    }

  } else {
    result.issues.warning.push("Geen zoekwoord opgegeven voor analyse.");
  }

  // 4. Structure & Length Analysis
  
  // Word Count
  if (result.wordCount < 300) {
    result.issues.critical.push("Tekst is te kort (< 300 woorden) voor goede ranking.");
    result.score -= 20;
  } else if (result.wordCount < 600) {
    result.issues.warning.push("Tekst is aan de korte kant (< 600 woorden).");
    result.score -= 5;
  } else {
    result.issues.good.push(`Goede lengte (${result.wordCount} woorden).`);
  }

  // Headings
  const headings = doc.querySelectorAll('h1, h2, h3, h4, h5, h6');
  if (headings.length < 2) {
    result.issues.warning.push("Gebruik meer tussenkoppen (H2/H3) voor structuur.");
    result.score -= 10;
  } else {
    result.issues.good.push("Goede structuur met tussenkoppen.");
  }

  // Zero-Click FAQ Check (New)
  // We check for the specific ID used in the generator (#faq-section) or generic details tags
  const faqSection = doc.querySelector('#faq-section');
  const faqItems = doc.querySelectorAll('details'); 
  
  if (!faqSection || faqItems.length < 3) {
      result.issues.warning.push("GEO TIP: Voeg minimaal 3 FAQ vragen toe voor 'Zero-Click' kansen in Google/AI.");
      result.score -= 10;
  } else {
      result.issues.good.push("FAQ sectie aanwezig (Goed voor Voice Search & Rich Snippets).");
  }

  // Paragraph length (Readability)
  const paragraphs = doc.querySelectorAll('p');
  let longParagraphs = 0;
  paragraphs.forEach(p => {
    const pWords = (p.textContent || "").split(/\s+/).length;
    if (pWords > 150) longParagraphs++; // > 150 words is very long for web
  });

  if (longParagraphs > 0) {
    result.issues.warning.push(`${longParagraphs} alinea's zijn te lang (>150 woorden).`);
    result.score -= 5;
  }

  // Images with Alt Text
  const images = doc.querySelectorAll('img');
  let missingAlt = 0;
  images.forEach(img => {
    if (!img.getAttribute('alt')) missingAlt++;
  });

  if (missingAlt > 0) {
    result.issues.warning.push(`${missingAlt} afbeeldingen missen een ALT tekst.`);
    result.score -= 5;
  } else if (images.length > 0) {
    result.issues.good.push("Alle afbeeldingen hebben ALT teksten.");
  }

  // Links
  const links = doc.querySelectorAll('a');
  if (links.length === 0) {
     result.issues.warning.push("Geen interne of externe links gevonden.");
     result.score -= 5;
  } else {
    result.issues.good.push(`${links.length} links gevonden.`);
  }

  // CRITICAL: Check for accidental noindex tags in content
  // Sometimes people copy-paste metadata into the body
  const metaRobots = doc.querySelector('meta[name="robots"]');
  if (metaRobots) {
      const content = metaRobots.getAttribute('content')?.toLowerCase() || "";
      if (content.includes('noindex')) {
          result.issues.critical.push("LET OP: Er staat een 'noindex' tag in je code. Google zal dit NIET indexeren.");
          result.score -= 50;
      }
  }

  // Cap Score
  result.score = Math.max(0, Math.min(100, result.score));

  return result;
};
